// Auto-extracted preset context and amp data
// PRESET_CONTEXT
const PRESET_CONTEXT = {
  "Marshall SL800":{emoji:"⚡",refs:[{a:"AC/DC",t:["Back in Black","Shoot to Thrill"]},{a:"Led Zeppelin",t:["Stairway to Heaven"]},{a:"Black Sabbath",t:["Paranoid"]}],desc:"Le Marshall SL800 incarne le hard rock des années 70-80. Grain british agressif, attaque percutante, sustain massif. Le son Angus Young (AC/DC) et Jimmy Page (Led Zeppelin) par excellence."},
  "Two Rock Stevie G":{emoji:"🌊",refs:[{a:"Eric Clapton",t:["White Room"]},{a:"Mark Knopfler",t:["Money for Nothing"]},{a:"John Mayer",t:["Gravity"]},{a:"SRV",t:["Pride and Joy"]}],desc:"Ampli boutique américain au son chaleureux et transparent. Cleans cristallins, crunch musical et dynamique exceptionnelle. Idéal pour les jeux expressifs en single coil."},
  "Marshall JTM45":{emoji:"🎩",refs:[{a:"Eric Clapton",t:["White Room","Sunshine of Your Love"]},{a:"Pete Townshend",t:["My Generation"]},{a:"Jimi Hendrix",t:["Voodoo Child"]}],desc:"Le premier Marshall, dérivé du Fender Bassman. Son de crunch bluesy intemporel, breakup naturel. Pilier du blues-rock britannique des années 60."},
  "Two Rock Bloomfield":{emoji:"🌿",refs:[{a:"Michael Bloomfield",t:["Like a Rolling Stone","Born in Chicago"]},{a:"Eric Clapton",t:[]},{a:"Peter Green",t:["The World is a Ghetto"]}],desc:"Inspiré du légendaire Bloomfield Drive. Cleans aériens, overdrive musical et naturel. La référence pour le blues électrique américain."},
  "Fender Super":{emoji:"🌅",refs:[{a:"Dick Dale",t:["Misirlou"]},{a:"Buddy Holly",t:["That'll Be the Day"]},{a:"SRV",t:["Couldn't Stand the Weather"]},{a:"Buddy Guy",t:["Couldn't Stand the Weather"]}],desc:"Le Fender Super Amp incarne le son américain pur : cleans brillants, réponse cristalline. Indispensable pour les Strats et Teles en son propre ou légèrement breaké."},
  "Dumble Deluxe":{emoji:"👑",refs:[{a:"BB King",t:["The Thrill Is Gone"]},{a:"Robben Ford",t:["Ain't That Peculiar","Inside Story"]},{a:"Carlos Santana",t:["Oye Como Va"]},{a:"Eric Clapton",t:[]}],desc:"Le Dumble est le Stradivarius des amplificateurs. Son ouvert, aéré, chaleur incomparable. BB King l'utilisait pour obtenir ce vibrato et ce sustain signature avec Lucille."},
  "Marshall Plexi":{emoji:"🔥",refs:[{a:"Jimi Hendrix",t:["All Along the Watchtower"]},{a:"Jimmy Page",t:["Whole Lotta Love"]},{a:"Eric Clapton",t:["Crossroads"]},{a:"Pete Townshend",t:["Won't Get Fooled Again"]}],desc:"L'ampli rock par excellence. Le Plexi définit le son du rock des années 60-70. Crunch chaud et harmonique, sustain naturel, réponse dynamique magistrale."},
  "D13 RG7":{emoji:"🎵",refs:[{a:"Derek Trucks",t:["Soul Serenade"]},{a:"Joe Bonamassa",t:["Sloe Gin"]},{a:"John Mayer",t:["Gravity"]}],desc:"Ampli boutique inspiré du son Tweed. Chaleureux, réactif, harmoniques riches. Particulièrement apprécié des bluesmen modernes."},
  "Fender Twin Silverface":{emoji:"🏙️",refs:[{a:"Muddy Waters",t:["Hoochie Coochie Man"]},{a:"BB King",t:["Three O'Clock Blues"]},{a:"The Rolling Stones",t:["Jumpin' Jack Flash"]},{a:"Dire Straits",t:[]}],desc:"Le Fender Twin Silverface : cleans légendaires, volume et headroom immenses. Le son Chicago Blues par excellence. Parfait pour les riffs stop-time et les solos expressifs."},
  "Marshall JCM900":{emoji:"🏟️",refs:[{a:"Deep Purple",t:["Smoke on the Water"]},{a:"Téléphone",t:["Flipper"]},{a:"Metallica",t:["Enter Sandman"]},{a:"Alice in Chains",t:["Rooster"]}],desc:"Le JCM900 incarne le son rock des années 80-90. Double canal, gain élevé, le son des stades. Blackmore (Deep Purple) et Bertignac (Téléphone) en ont fait leur marque."},
  "TSR20":{emoji:"🎸",refs:[{a:"Nirvana",t:["Come as You Are"]},{a:"Foo Fighters",t:["Everlong"]},{a:"Green Day",t:["Basket Case"]}],desc:"Ampli boutique de TSR inspiré du son alternatif des années 90. Grain épais, crunch agressif, sustain massif. Idéal pour les riffs grunge et post-grunge."},
  "Marshall 800":{emoji:"🤘",refs:[{a:"Slash",t:["Sweet Child O' Mine"]},{a:"Angus Young",t:["Hell's Bells"]},{a:"Gary Moore",t:["Still Got the Blues"]},{a:"Def Leppard",t:["Pour Some Sugar on Me"]}],desc:"Le JCM800 est l'ampli hard rock emblématique des années 80. Gain structuré, son puissant et percutant. Slash (Guns N' Roses) et Gary Moore en ont fait leur signature."},
  "Fender Deluxe":{emoji:"☀️",refs:[{a:"Stevie Ray Vaughan",t:["Pride and Joy"]},{a:"John Mayer",t:["Slow Dancing in a Burning Room"]},{a:"BB King",t:["Lucille"]},{a:"Albert Collins",t:["Frosty"]}],desc:"Le Fender Deluxe Reverb : l'ampli blues américain idéal. Breakup naturel, réverb à ressort intégrée, son chaud et musical. Parfait pour les Strats et les solos expressifs."},
  "Friedman BE-100":{emoji:"💥",refs:[{a:"Megadeth",t:["Holy Wars"]},{a:"Whitesnake",t:["Here I Go Again"]},{a:"Dave Friedman",t:["Reckless Road"]}],desc:"Le Friedman BE-100 (Brown Eye) est un modern classic du hard rock. Basé sur un Plexi modifié, il offre clarté et gain massif en même temps."},
  "Friedman HBE":{emoji:"💀",refs:[{a:"Metallica",t:["Master of Puppets"]},{a:"Slayer",t:["Raining Blood"]},{a:"Tool",t:["The Pot"]}],desc:"Le Friedman HBE (Hairy Brown Eye) pousse le concept BE encore plus loin avec plus de gain et d'agressivité. Idéal pour le metal moderne."},
  "Vox AC30":{emoji:"🫖",refs:[{a:"The Beatles",t:["A Hard Day's Night"]},{a:"Queen",t:["Bohemian Rhapsody"]},{a:"The Kinks",t:["You Really Got Me"]},{a:"Radiohead",t:["Creep"]}],desc:"Le son britannique vintage par excellence. Le Vox AC30 avec ses lampes EL84 produit des harmoniques uniques, des cleans cristallins et un crunch musical. Incontournable pour le rock british."},
  "Roland JC-120":{emoji:"🌐",refs:[{a:"Andy Summers",t:["Every Breath You Take"]},{a:"Robert Smith",t:["Lovesong","Close to Me"]},{a:"Chic Corea",t:[]}],desc:"Le seul ampli à transistors vraiment légendaire. Son stéréo clean parfait, chorus intégré. Andy Summers (The Police) et Robert Smith (The Cure) en ont fait leur signature."},
  "Orange Rockerverb":{emoji:"🍊",refs:[{a:"Jim Root",t:["Before I Forget"]},{a:"Noel Gallagher",t:["Don't Look Back in Anger"]},{a:"Mastodon",t:["Oblivion"]}],desc:"L'Orange Rockerverb allie le son chaud et british de la marque à la possibilité de gain élevé. Son épais, harmoniques riches, caractère très distinctif."},
  "Mesa Rectifier":{emoji:"🔴",refs:[{a:"Metallica",t:["The Unforgiven"]},{a:"Tool",t:["Schism"]},{a:"System of a Down",t:["B.Y.O.B."]},{a:"Deftones",t:["Change"]}],desc:"Le Rectifier de Mesa/Boogie a redéfini le son du metal moderne. Gain massif, basses profondes, mur de son impressionnant. Essentiel pour le metal des années 90-2000."},
  "Mesa Mark IV":{emoji:"🎯",refs:[{a:"Carlos Santana",t:["Oye Como Va"]},{a:"John Petrucci",t:["Pull Me Under"]},{a:"Metallica (early)",t:["Fade to Black"]}],desc:"Le Mesa Mark IV est l'ampli lead par excellence. Son articulé en clean, crunch musical, lead singing. John Petrucci (Dream Theater) le caractérise particulièrement."},
  "Peavey 5150":{emoji:"⚡",refs:[{a:"Eddie Van Halen",t:["Eruption"]},{a:"Slayer",t:["Raining Blood"]},{a:"Dimebag Darrell",t:["Walk"]}],desc:"Conçu avec Eddie Van Halen, le 5150 est l'ampli metal ultime. Gain agressif, son percutant, mur de son. Pilier du metal américain des années 90."},
  "Marshall SL100":{emoji:"⚡",refs:[{a:"Angus Young",t:["Highway to Hell"]},{a:"Bon Scott",t:["Highway to Hell"]},{a:"Brian Johnson",t:["TNT","Whole Lotta Rosie"]}],desc:"La tête Marshall Super Lead 100W : le son brut du rock. Utilisée par AC/DC pour leur son légendaire, couplée à un Marshall 4x12. Puissance et agressivité naturelles."},
  "Marshall JTM50":{emoji:"🎩",refs:[{a:"Eric Clapton",t:["Crossroads","Sunshine of Your Love"]},{a:"Cream",t:["Crossroads","Sunshine of Your Love"]},{a:"Peter Green",t:["Black Magic Woman"]}],desc:"Le JTM50 est la version 50W du JTM45, avec une sonorité légèrement plus comprimée et harmonique. Utilisé par Clapton avec Cream pour les premiers albums blues-rock."},
  "Marshall JC800":{emoji:"🤘",refs:[{a:"Billy Idol",t:["White Wedding"]},{a:"Accept",t:["Balls to the Wall"]},{a:"Motörhead",t:["Ace of Spades"]}],desc:"Le Marshall JCM800 dans sa version rack. Le son hard rock / heavy metal des années 80, agressif et défini. Paire bien avec toute guitare à humbuckers."},
  "Marshall SB100":{emoji:"🎸",refs:[{a:"Ritchie Blackmore",t:["Highway Star"]},{a:"Jimmy Page",t:["Immigrant Song"]},{a:"Paul Kossoff",t:["All Right Now"]}],desc:"Le Super Bass Marshall, utilisé par les guitaristes rock des années 70 pour sa réponse plus grave et son breakup naturel. Blackmore (Deep Purple) adorait son crunch."},
  "Orange 120":{emoji:"🍊",refs:[{a:"Randy Rhoads",t:["Crazy Train"]},{a:"Fleetwood Mac",t:["Oh Well"]},{a:"Geezer Butler",t:["Iron Man"]}],desc:"L'Orange de 120W : volume massif, son chaud et british, crunch naturel. Utilisé par Randy Rhoads en début de carrière et de nombreux guitaristes hard rock britanniques."},
  "Orange GR100":{emoji:"🍊",refs:[{a:"Jim Root",t:["Before I Forget"]},{a:"Opeth",t:["Ghost of Perdition"]},{a:"Wolfmother",t:["Woman"]}],desc:"L'Orange Graphic 100 incarne le son rock british vintage. Chaud, crunchant, avec une saturation naturelle. Parfait pour le hard rock des années 70."},
  "Fender Blackface Twin":{emoji:"🌟",refs:[{a:"The Rolling Stones",t:["Brown Sugar"]},{a:"Dire Straits",t:["Sultans of Swing"]},{a:"SRV",t:["Texas Flood"]}],desc:"Le Fender Twin Blackface est la référence absolue des cleans américains. Headroom énorme, brillance cristalline. Utilisé par des générations de guitaristes pour sa neutralité et sa dynamique."},
  "Fender BF Deluxe":{emoji:"🌅",refs:[{a:"Neil Young",t:["Heart of Gold"]},{a:"SRV",t:["Couldn't Stand the Weather"]},{a:"John Mayer",t:["Neon"]}],desc:"Le Fender Deluxe Reverb Blackface : le son américain des années 60. Reverb à ressort intégrée, clean chaleureux qui se salit légèrement quand on pousse le volume."},
  "Fender Tweed Deluxe":{emoji:"🎶",refs:[{a:"Buddy Holly",t:["That'll Be the Day"]},{a:"Chuck Berry",t:["Johnny B. Goode"]},{a:"Neil Young",t:["Cinnamon Girl"]}],desc:"Le Fender Champ/Deluxe Tweed : le son américain originel. Breakup naturel à faible volume, harmoniques riches, le son qui a défini le rock'n'roll."},
  "Fender Tweed Bassman":{emoji:"🎷",refs:[{a:"Buddy Guy",t:["Stone Crazy"]},{a:"Muddy Waters",t:["Mannish Boy"]},{a:"Eric Clapton",t:["Five Long Years"]}],desc:"Le Fender Tweed Bassman a inspiré les premiers Marshall. Son rond et chaud, crunch musical, le son du Chicago Blues par excellence."},
  "Fender Blonde Bassman":{emoji:"👑",refs:[{a:"BB King",t:["The Thrill Is Gone"]},{a:"Albert King",t:["Born Under a Bad Sign"]},{a:"Freddie King",t:["Hideaway"]}],desc:"Le Fender Blonde Bassman : son épais et chaud, à mi-chemin entre le Tweed et le Blackface. Les rois du blues en faisaient un usage extensif."},
  "Hiwatt Custom 100":{emoji:"🇬🇧",refs:[{a:"The Who",t:["Won't Get Fooled Again"]},{a:"Pink Floyd",t:["Comfortably Numb","Wish You Were Here"]},{a:"Roger Waters",t:["Wish You Were Here"]}],desc:"Le Hiwatt Custom 100 : volume et headroom incomparables, son british cristallin et défini. Pete Townshend (The Who) et David Gilmour (Pink Floyd) en ont fait leur signature."},
  "Mesa Mark IIC+":{emoji:"⚗️",refs:[{a:"Metallica",t:["Fade to Black"]},{a:"John Petrucci",t:["Pull Me Under"]},{a:"Carlos Santana",t:["Oye Como Va"]}],desc:"Le Saint Graal des amplis. James Hetfield de Metallica l'a utilisé sur 'Ride the Lightning' et 'Master of Puppets'. Son lead articulé, gain massif, l'un des amplis les plus recherchés."},
  "Dumble ODS 124":{emoji:"💎",refs:[{a:"Robben Ford",t:["Inside Story"]},{a:"Larry Carlton",t:["Room 335"]},{a:"BB King",t:["Every Day I Have the Blues"]},{a:"Eric Clapton",t:["Every Day I Have the Blues"]}],desc:"Le Dumble ODS (Overdrive Special) est l'ampli le plus exclusif au monde. Son transparent et dynamique, overdrive naturel et musical. Prisé par les meilleurs guitaristes blues-rock."},
  "Gibson GA5 Skylark":{emoji:"🎵",refs:[{a:"Chuck Berry",t:["Johnny B. Goode"]},{a:"Carl Perkins",t:["Blue Suede Shoes"]},{a:"Bo Diddley",t:["Who Do You Love"]}],desc:"Le petit ampli Gibson GA5 : le son roots américain des années 50. Breakup naturel à faible volume, chaleur vintage. Particulièrement adapté aux P90 pour ce son rockabilly/blues originel."},
  "Marshall Plexi 74":{emoji:"🏺",refs:[{a:"Jimi Hendrix",t:["Purple Haze"]},{a:"Eric Clapton",t:["Crossroads"]},{a:"The Who",t:["My Generation"]},{a:"Led Zeppelin",t:["Rock and Roll"]}],desc:"Le Marshall Plexi 1974 : version avec master volume permettant plus de flexibilité. Son hard rock classique des années 70, harmoniques riches, crunch naturel à fort volume."},
  "Matchless":{emoji:"🎼",refs:[{a:"Tom Petty",t:["Free Fallin'","I Won't Back Down"]},{a:"Grant Green",t:[]},{a:"Tom Bukovac",t:["Refugee"]}],desc:"Le Matchless DC30 : l'héritier moderne du Vox AC30. Son plus articulé et hi-fi, cleans brillants et crunch musical. Très apprécié des guitaristes de session et des amateurs de son vintage moderne."},
  "Cornford HellCat":{emoji:"😈",refs:[{a:"Radiohead",t:["Karma Police"]},{a:"Muse",t:["Hysteria"]},{a:"Mark Knopfler",t:["Walk of Life"]}],desc:"L'ampli britannique boutique par excellence. Le Cornford HellCat offre des cleans soyeux et un crunch naturel. Apprécié pour sa réponse dynamique et sa polyvalence."},
  "Chandler GAV19T":{emoji:"☕",refs:[{a:"The Beatles",t:["A Hard Day's Night"]},{a:"Roy Orbison",t:["Oh, Pretty Woman"]},{a:"The Kinks",t:["Waterloo Sunset"]}],desc:"Réplique du Vox AC15 vintage. Son brillant et chimeux, résonance musicale des lampes EL84. Le son pop british des années 60."},
  "Marshall JCM800":{emoji:"🤘",refs:[{a:"Slash",t:["Paradise City"]},{a:"Gary Moore",t:["Still Got the Blues"]},{a:"Iron Maiden",t:["The Trooper"]},{a:"Judas Priest",t:["Breaking the Law"]}],desc:"Le JCM800 est THE ampli hard rock des années 80. Son agressif et défini, gain structuré, le son de toute une génération de guitaristes hard rock et heavy metal."},
  "Soldano SLO-100":{emoji:"💎",refs:[{a:"Eric Clapton",t:["Lay Down Sally (live)"]},{a:"Gary Moore",t:["Still Got the Blues"]},{a:"Mike McCready (Pearl Jam)",t:["Alive"]},{a:"Warren Haynes",t:["Soulshine"]}],desc:"Le Soldano SLO-100 est l'une des têtes les plus prisées du rock et du blues moderne. Gain transparent, dynamique impressionnante, son articulé à tous les niveaux. Clapton et Gary Moore en étaient fans."},
  "Soldano GP77":{emoji:"💎",refs:[{a:"Eric Clapton",t:["Tears in Heaven (live)"]},{a:"Lou Reed",t:["Perfect Day"]},{a:"The Smiths",t:["How Soon Is Now"]}],desc:"Le Soldano GP77 est un préampli rack de légende, base du SLO-100. Son cristallin en clean, saturation progressive et musicale. Très utilisé dans les studios des années 80-90."},
  "Bogner Ecstasy":{emoji:"🔮",refs:[{a:"Steve Lukather",t:["Rosanna"]},{a:"John Petrucci",t:["Pull Me Under"]},{a:"Eddie Van Halen",t:["Panama"]}],desc:"Le Bogner Ecstasy est un ampli boutique à plusieurs canaux offrant une polyvalence exceptionnelle. Clean cristallin, crunch british et lead moderne. Steve Lukather (Toto) et John Petrucci en sont de grands utilisateurs."},
  "Bogner G-Finger":{emoji:"🔮",refs:[{a:"Steve Howe",t:["Roundabout"]},{a:"Alex Lifeson",t:["Tom Sawyer"]},{a:"Joe Satriani",t:["Surfing with the Alien"]}],desc:"Ampli boutique Bogner au son chaud et complexe. Particulièrement apprécié des guitaristes de rock progressif pour sa richesse harmonique et sa réactivité au jeu."},
  "Bogner Helioclipse":{emoji:"🌀",refs:[{a:"Mike Landau",t:["Session work"]},{a:"Tom Quayle",t:["Smooth Jazz"]},{a:"John Petrucci",t:["Distance Over Time"]}],desc:"Le Bogner Helioclipse est un ampli moderne à la sonorité cristalline et transparente. Très prisé des guitaristes de fusion et de rock progressif pour ses qualités de studio."},
  "Diesel Humbert":{emoji:"⚙️",refs:[{a:"Devin Townsend",t:["Ocean Machine"]},{a:"Guthrie Govan",t:["Erotic Cakes"]},{a:"Shawn Lane",t:["Powers of Ten"]}],desc:"Le Diesel/VHT Humbert est un ampli boutique allemand au son tight et agressif. Très articulé dans les graves, idéal pour le metal et le hard rock moderne."},
  "Marshall SLT60":{emoji:"⚡",refs:[{a:"Jimmy Page",t:["Whole Lotta Love"]},{a:"Eric Clapton",t:["Crossroads"]},{a:"Peter Green",t:["Black Magic Woman"]}],desc:"Le Marshall Silver Jubilee SLT60 est la version 60W du légendaire 2555. Son crunch dynamique et ses médiums prononcés en font un ampli incontournable du rock."},
  "Matchless DC30":{emoji:"🎼",refs:[{a:"Tom Petty",t:["American Girl"]},{a:"Thurston Moore",t:["Teen Age Riot"]},{a:"Grant Green",t:["Idle Moments"]}],desc:"Le Matchless DC30 : l'héritier moderne du Vox AC30. Plus articulé et hi-fi, ses cleans sont brillants et son crunch exceptionnel. Très apprécié des guitaristes de session et des amateurs de son vintage moderne."},
  "Matchless HC15":{emoji:"🎼",refs:[{a:"Peter Buck (R.E.M.)",t:["Losing My Religion"]},{a:"Johnny Marr",t:["This Charming Man"]},{a:"Andy Summers",t:["Every Breath You Take"]}],desc:"Le Matchless HC15 en version 15W : son british vintage ultra-musical. Cleans brillants, crunch expressif, réponse dynamique remarquable. Idéal pour le rock indé et le post-punk."},
  "Matchless Independence 35":{emoji:"🎼",refs:[{a:"John Frusciante",t:["Under the Bridge"]},{a:"Jonny Greenwood",t:["Karma Police"]},{a:"Dave Grohl",t:["Best of You"]}],desc:"Le Matchless Independence 35 est l'ampli double canal de Matchless. Clean impeccable, overdrive musical. Utilisé par John Frusciante sur de nombreux enregistrements avec les RHCP."},
  "Hiwatt HG100":{emoji:"🇬🇧",refs:[{a:"Pete Townshend",t:["Won't Get Fooled Again"]},{a:"Ritchie Blackmore",t:["Highway Star"]},{a:"David Gilmour",t:["Comfortably Numb"]}],desc:"Le Hiwatt HG100 avec ses modifications gain : le son british puissant et agressif. Dérivé du légendaire DR103, il conserve cette clarté et ce headroom caractéristiques tout en ajoutant de la saturation."},
  "Hiwatt Wizard":{emoji:"🧙",refs:[{a:"Dave Murray",t:["The Trooper","Aces High"]},{a:"Adrian Smith",t:["Aces High"]},{a:"Michael Schenker",t:["Rock You Like a Hurricane"]}],desc:"Combinaison du son britannique Hiwatt avec les capacités haute gain d'un Wizard. Son puissant, articulé, idéal pour le heavy metal et le hard rock des années 80."},
  "Budda V20":{emoji:"🏔️",refs:[{a:"Billy Gibbons",t:["Sharp Dressed Man"]},{a:"Joe Walsh",t:["Life's Been Good"]},{a:"Warren Haynes",t:["Soulshine"]}],desc:"Le Budda V20 est un petit combo américain au son tweed moderne. Breakup naturel, chaleur incomparable, dynamique réactive. Très apprécié pour les blues et rock américain."},
  "D13 AMP39":{emoji:"🎵",refs:[{a:"Derek Trucks",t:["Whipping Post (live)"]},{a:"Doyle Bramhall II",t:["It's Not Easy Being Green"]},{a:"Gary Clark Jr.",t:["Bright Lights"]}],desc:"Le D13 AMP39 est un ampli boutique canadien inspiré des circuits des années 40-50. Son vintage et chaud, réponse organique, idéal pour le blues moderne et le soul rock."},
  "Fender Concert":{emoji:"🌟",refs:[{a:"Buddy Holly",t:["That'll Be the Day"]},{a:"Chuck Berry",t:["Roll Over Beethoven"]},{a:"James Burton",t:["Mystery Train"]}],desc:"Le Fender Concert 4x10 : puissance américaine, son clean et percutant. Intermédiaire entre le Deluxe et le Twin, parfait pour les single coils qui cherchent clarté et headroom."},
  "Fender Deluxe Reverb":{emoji:"🌅",refs:[{a:"Neil Young",t:["Heart of Gold"]},{a:"SRV",t:["Couldn't Stand the Weather"]},{a:"John Mayer",t:["Slow Dancing in a Burning Room"]},{a:"Albert King",t:[]}],desc:"Le Fender Deluxe Reverb est l'ampli américain vintage idéal. Reverb à ressort intégrée, clean chaleureux qui se casse légèrement quand on pousse le volume. Une référence absolue pour le blues et la country."},
  "Fender Champ":{emoji:"🎵",refs:[{a:"Hound Dog Taylor",t:["Taylor's Rock"]},{a:"Robert Johnson Jr.",t:["Various blues recordings"]},{a:"Eddie Cochran",t:["Summertime Blues"]}],desc:"Le petit Fender Champ : son intime, breakup très expressif à faible volume. Les enregistrements de blues Chicago des années 50 doivent beaucoup à cet ampli."},
  "Fender 5051 Tweed":{emoji:"🎶",refs:[{a:"Carl Perkins",t:["Blue Suede Shoes"]},{a:"Sun Records artists",t:["Mystery Train"]},{a:"Elvis Presley (Scott Moore)",t:["That's All Right"]}],desc:"Le Fender Tweed des années 50 : le son originel du rock'n'roll. Breakup naturel et musical, midrange chaleureux. Les sessions Sun Records de Memphis ont défini ce son."},
  "Friedman Buxom Betty":{emoji:"💥",refs:[{a:"The Dead Daisies",t:["Highway Star (cover)"]},{a:"Zakk Wylde",t:["Bark at the Moon"]},{a:"Jerry Cantrell",t:["Would?"]}],desc:"La Friedman Buxom Betty est une tête au son chaud et puissant, moins agressif que la BE-100. Crunch british, sustain impressionnant, très polyvalente pour le hard rock."},
  "Cornford HellCat":{emoji:"😈",refs:[{a:"Radiohead",t:["Karma Police"]},{a:"Muse",t:["Hysteria"]},{a:"Mark Knopfler",t:["Walk of Life"]}],desc:"L'ampli britannique boutique par excellence. Cleans soyeux, crunch naturel, réponse dynamique remarquable. Particulièrement apprécié pour sa polyvalence des jeux rythmiques aux solos."},
  "Cornford Harle":{emoji:"😈",refs:[{a:"Thom Yorke",t:["The Bends era"]},{a:"Tom Morello (alt.)",t:["Rage setup"]},{a:"Nile Rodgers",t:["Le Freak"]}],desc:"Le Cornford Harle est la version clean/crunch de la gamme Cornford. Son aéré, réponse en cloche, idéal pour les jeux dynamiques et les textures sonores recherchées."},
  "Chandler 19T":{emoji:"🧪",refs:[{a:"The Beatles",t:["Please Please Me"]},{a:"Gerry & The Pacemakers",t:["You'll Never Walk Alone"]},{a:"The Shadows",t:["Apache"]}],desc:"Le Chandler 19T est une réplique du Vox AC15 des années 60 avec préampli modificable. Le son de la British Invasion originel, cleans brillants, chime caractéristique des lampes EL84."},
  "Electro Dime":{emoji:"⚡",refs:[{a:"Jeff Beck",t:["Freeway Jam"]},{a:"Robin Trower",t:["Bridge of Sighs"]},{a:"Roy Buchanan",t:["Sweet Dreams"]}],desc:"Ampli boutique au son transparent et dynamique. Particulièrement apprécié pour les single coils, il produit des harmoniques riches et une réponse très expressive au toucher."},
  "Reinguard T-36":{emoji:"🎸",refs:[{a:"Gary Moore",t:["Still Got the Blues"]},{a:"Rory Gallagher",t:["Moonchild"]},{a:"Robin Trower",t:["Day of the Eagle"]}],desc:"Le Reinguard T-36 est un ampli boutique au son vintage british. Son chaud et réactif, midrange prononcé, très apprécié pour le blues-rock et le rock classique."},
  "Rouge Plate D50":{emoji:"🎭",refs:[{a:"Robben Ford",t:["Talk to Your Daughter"]},{a:"Larry Carlton",t:["Room 335","Captain Caribe"]},{a:"Lee Ritenour",t:["Captain Caribe"]}],desc:"Le Rouge Plate D50 offre un son jazz-fusion d'exception. Clean transparent, overdrive musical et articulé. Très utilisé par les guitaristes de jazz-fusion et de soul."},
  "Silver J":{emoji:"⚡",refs:[{a:"Randy Bachman",t:["American Woman"]},{a:"Angus Young (alt.)",t:["Highway to Hell alt."]},{a:"Ted Nugent",t:["Cat Scratch Fever"]}],desc:"Ampli boutique inspiré du Silver Jubilee de Marshall. Son dynamique et puissant, crunch explosif, midrange expressif. Parfait pour le hard rock et le classic rock."},
  "Independence 35":{emoji:"🎼",refs:[{a:"John Frusciante",t:["Give It Away"]},{a:"Kim Thayil",t:["Black Hole Sun"]},{a:"Mike McCready",t:["Even Flow"]}],desc:"Ampli multi-canaux offrant une grande palette sonore. Apprécié du rock alternatif américain des années 90 pour sa flexibilité et sa musicalité."},
  "Jimi H20":{emoji:"🔥",refs:[{a:"Jimi Hendrix",t:["Purple Haze","Machine Gun"]},{a:"Stevie Ray Vaughan",t:["Pride and Joy"]},{a:"Billy Cox",t:[]}],desc:"Ampli inspiré par le setup de Jimi Hendrix — un circuit basé sur le Marshall modifié. Son légendaire : cleans cristallins qui se cassent naturellement, feedback musical, sustain infini."},
  "Talon 50":{emoji:"🦅",refs:[{a:"Brad Paisley",t:["Mud on the Tires"]},{a:"Keith Urban",t:["You'll Think of Me"]},{a:"Brent Mason",t:["Guitar Man"]}],desc:"Amplificateur boutique américain au son country/rock moderne. Cleans brillants, crunch twangy, réponse parfaite pour les Telecasters et les styles country et roots rock."},
  "VMP-1":{emoji:"🎸",refs:[{a:"Carlos Santana",t:["Smooth"]},{a:"Gary Moore",t:["Still Got the Blues"]},{a:"George Lynch",t:["Mr. Scary"]}],desc:"Le VMP-1 (Vacuum Microphone Preamplifier) est un préampli rack à lampes légendaire. Son chaud et transparent, utilisé dans de nombreux studios pour son caractère analogique distinctif."},
  "Sons Amplification":{emoji:"🎵",refs:[{a:"Stevie Ray Vaughan (inspired)",t:["Texas Flood"]},{a:"BB King",t:["The Thrill Is Gone"]},{a:"Buddy Guy",t:["First Time I Met the Blues"]}],desc:"Sons Amplification produit des amplis boutique au son blues américain authentique. Inspirés des grands classiques Fender et Dumble, ils offrent une dynamique et une chaleur exceptionnelles."},
  "TWS 2864-S":{emoji:"🎸",refs:[{a:"Ritchie Blackmore",t:["Highway Star"]},{a:"Glenn Tipton",t:["Screaming for Vengeance"]},{a:"K.K. Downing",t:["Breaking the Law"]}],desc:"Ampli boutique au son british puissant et défini. Inspiré des grandes têtes Marshall 100W des années 70-80, idéal pour le hard rock et le heavy metal classique."},
  "Amp Nation WOD":{emoji:"🎸",refs:[{a:"Dave Grohl",t:["Everlong"]},{a:"Billy Corgan",t:["Bullet with Butterfly Wings"]},{a:"Stone Gossard",t:["Even Flow"]}],desc:"Ampli au son grunge/alternative des années 90. Mur de son compressé, sustain massif, grain agressif. Tout ce dont le rock alternatif américain avait besoin."},
  "Amp Nation ODR":{emoji:"🎸",refs:[{a:"Brad Whitford",t:["Walk This Way"]},{a:"Joe Perry",t:["Sweet Emotion"]},{a:"Slash",t:["Mr. Brownstone"]}],desc:"Ampli boutique overdrive orienté rock classique américain. Son chaud et percutant, réponse dynamique, grain characteristique du rock américain des années 70-80."},
  "Ironlung":{emoji:"🤖",refs:[{a:"Josh Homme",t:["No One Knows"]},{a:"Nick Oliveri",t:["Millionaire"]},{a:"Omar Rodríguez-López",t:["Roulette Dares"]}],desc:"Ampli boutique au son épais et psych. Apprécié du stoner rock et du rock psychédélique pour son grain unique, son sustain naturel et son caractère sonore distinctif."},
  "ZWREK":{emoji:"⚡",refs:[{a:"Various rock artists",t:["Rock moderne"]},{a:"Boutique users",t:["Hard rock contemporain"]}],desc:"Ampli boutique ZWREK au son moderne et puissant. Polyvalent, du clean transparent au gain élevé, avec une réponse articulée très appréciée des guitaristes modernes."},
  "Dumble ODS":{emoji:"💎",refs:[{a:"Robben Ford",t:["Inside Story"]},{a:"Larry Carlton",t:["Room 335"]},{a:"BB King",t:["Every Day I Have the Blues"]},{a:"Eric Clapton",t:["Every Day I Have the Blues"]}],desc:"Le Dumble ODS (Overdrive Special) est l'ampli le plus exclusif au monde. Son transparent et dynamique, overdrive naturel et musical. Prisé par les meilleurs guitaristes blues-rock au monde."},
  "Mesa Boogie Rectifier":{emoji:"🔴",refs:[{a:"Metallica",t:["The Unforgiven"]},{a:"Tool",t:["Schism"]},{a:"System of a Down",t:["B.Y.O.B."]},{a:"Deftones",t:["Change"]}],desc:"Le Rectifier de Mesa/Boogie a redéfini le son du metal moderne. Gain massif, basses profondes, mur de son impressionnant. Essentiel pour le metal des années 90-2000."},
  "GK MB150":{emoji:"🎸",refs:[{a:"Stanley Clarke",t:["School Days"]},{a:"Jaco Pastorius",t:["Portrait of Tracy"]},{a:"Marcus Miller",t:["Run for Cover"]}],desc:"Le GK MB150 est une référence pour la basse électrique. Son articulé et percutant, parfait pour le jazz, la fusion et le funk. Marcus Miller et Stanley Clarke l'utilisaient régulièrement."},
  "Ampeg SVT Pro 4":{emoji:"🎸",refs:[{a:"Geddy Lee",t:["YYZ"]},{a:"John Paul Jones",t:["Whole Lotta Love"]},{a:"Mike Dirnt",t:["Basket Case"]}],desc:"L'Ampeg SVT Pro 4 est une légende de la basse. Son massif et chaud, caractéristique du rock classique. Geddy Lee (Rush) et John Paul Jones (Led Zeppelin) lui ont rendu hommage."},
  "Ampeg Bass":{emoji:"🎸",refs:[{a:"Paul McCartney",t:["Come Together"]},{a:"Dee Dee Ramone",t:["Blitzkrieg Bop"]},{a:"Geezer Butler",t:["Iron Man"]}],desc:"Les amplis Ampeg pour basse sont des références absolues dans le rock. Son ample, punchy, avec cette chaleur lampiste caractéristique qui a défini le son du rock classique."},
  "Aguilar DB750":{emoji:"🎸",refs:[{a:"Marcus Miller",t:[]},{a:"Victor Wooten",t:[]}],desc:"L'Aguilar DB750 est une tête basse à lampes au son chaud et massif. Référence absolue pour le funk, le jazz et le R&B. Son gros et rond avec une dynamique remarquable."},
  "Ampeg SVT":{emoji:"🎸",refs:[{a:"Lemmy Kilmister",t:["Ace of Spades"]},{a:"Chris Squire",t:["Roundabout"]},{a:"Flea",t:["Give It Away"]}],desc:"L'Ampeg SVT est LA référence basse depuis 1969. Son massif, puissant, avec une chaleur incomparable. Utilisé sur d'innombrables enregistrements rock et funk."},
  "Amplifonics":{emoji:"🎸",refs:[{a:"Session guitarists",t:[]}],desc:"Ampli boutique Amplifonics au son polyvalent. Cleans transparents, gain progressif et musical. Apprécié des guitaristes de session pour sa réponse dynamique et sa palette sonore étendue."},
  "Bad Cat Cub":{emoji:"🐱",refs:[{a:"Joe Walsh",t:["Life's Been Good"]},{a:"Warren Haynes",t:["Soulshine"]}],desc:"Le Bad Cat Cub est un petit combo américain inspiré des circuits Fender Tweed. Son chaleureux, breakup naturel à faible volume. Parfait pour le blues et le rock roots en studio."},
  "Benson Chimera":{emoji:"🌟",refs:[{a:"Julian Lage",t:[]},{a:"Cory Wong",t:[]}],desc:"Le Benson Chimera est un ampli boutique de Portland au son vintage moderne. Cleans soyeux, breakup expressif. Très prisé des guitaristes de jazz moderne et de funk."},
  "Carr Sportsman":{emoji:"☀️",refs:[{a:"Bill Frisell",t:[]},{a:"Blake Mills",t:[]}],desc:"Le Carr Sportsman est un ampli boutique américain au son Fender-like raffiné. Cleans cristallins, réverb intégrée, breakup musical. Idéal pour le jazz, le country et le blues propre."},
  "Cornfield Harle":{emoji:"😈",refs:[{a:"Thom Yorke",t:[]},{a:"Nile Rodgers",t:["Le Freak"]}],desc:"Le Cornford Harlequin est la version clean/crunch de Cornford. Son aéré, réponse en cloche, idéal pour les textures sonores et les jeux dynamiques."},
  "Custom 30":{emoji:"🫖",refs:[{a:"Brian May",t:["Bohemian Rhapsody"]},{a:"Tom Petty",t:["Free Fallin'"]}],desc:"Ampli de type Vox AC30 custom. Son british classique avec ses harmoniques chimey caractéristiques. Chime et crunch naturel pour le rock britannique."},
  "Diezel":{emoji:"⚙️",refs:[{a:"Adam Jones",t:["Schism"]},{a:"Bumblefoot",t:[]},{a:"Rivera (Metallica tech)",t:[]}],desc:"Les amplis Diezel allemands sont des machines de guerre du high gain. Son serré, articulé même dans les graves. Référence du metal et du hard rock moderne."},
  "Divided by 13":{emoji:"🔷",refs:[{a:"John Mayer",t:["Gravity","Waiting on the World to Change"]},{a:"Blake Mills",t:[]},{a:"Matt Schofield",t:[]}],desc:"Divided by 13 fabrique des amplis boutique californiens réputés pour leur dynamique exceptionnelle et leur réponse au toucher. Son clean lumineux qui crunche naturellement en poussant le volume. Favori de John Mayer en studio."},
  "Sons Amp":{emoji:"🔊",refs:[{a:"Session musicians",t:[]}],desc:"Sons Amplification est un fabricant d'amplis boutique britannique. Connus pour leur polyvalence, du clean cristallin au crunch rock classique. Amplis à lampes construits à la main avec un caractère british prononcé."},
  "Amplifonics":{emoji:"🔊",refs:[],desc:"Amplifonics est une marque d'amplis boutique orientée gain et polyvalence. Ces presets capturent différentes configurations de gain, du clean au lead, pour explorer la palette complète de l'ampli."},
  "Dr. Z":{emoji:"🩺",refs:[{a:"Brad Paisley",t:["Mud on the Tires"]},{a:"Joe Bonamassa",t:["Sloe Gin"]}],desc:"Les amplis Dr. Z sont des boutiques américains au son vintage inspiré du Vox et du Fender. Chaleur, réponse dynamique et musicalité exceptionnelles."},
  "Dr. Z Wreck":{emoji:"🩺",refs:[{a:"Joe Bonamassa",t:["Sloe Gin"]},{a:"Brad Paisley",t:[]}],desc:"Le Dr. Z Wreck est un ampli boutique inspiré du Trainwreck. Son clair brillant, crunch musical et expressif. Très réactif au volume de la guitare."},
  "Drive Pedals":{emoji:"🎛️",refs:[],desc:"Pédales de drive capturées via ToneX. Ces presets modélisent des pédales d'overdrive, fuzz et distortion populaires. A utiliser en standalone ou devant un ampli clean pour ajouter du gain et de la couleur."},
  "Pédales de drive":{emoji:"🎛️",refs:[],desc:"Captures de pédales de drive seules (sans ampli). A brancher devant un ampli clean dans votre chaîne de signal pour obtenir le caractère de la pédale tout en gardant le son de votre ampli."},
  "Pédales de drive + Boss BD-2 Blues Driver":{emoji:"🎛️",refs:[{a:"John Mayer",t:["Gravity"]},{a:"Kirk Hammett",t:[]}],desc:"Le Boss BD-2 Blues Driver est un overdrive transparent et dynamique. Très populaire pour le blues et le rock, il ajoute du crunch sans masquer le son de la guitare. Capture pédale seule."},
  "Pédales de drive + Dallas Arbiter Fuzz Face":{emoji:"🎛️",refs:[{a:"Jimi Hendrix",t:["Purple Haze","Foxy Lady"]},{a:"Eric Johnson",t:["Cliffs of Dover"]},{a:"David Gilmour",t:["Money"]}],desc:"Le Fuzz Face est LA pédale de Jimi Hendrix. Son fuzz organique, chaud et musical réagit au volume de la guitare. Capture pédale seule."},
  "Pédales de drive + EHX Big Muff":{emoji:"🎛️",refs:[{a:"David Gilmour",t:["Comfortably Numb"]},{a:"The Smashing Pumpkins",t:["Cherub Rock"]},{a:"Dinosaur Jr.",t:["Feel the Pain"]}],desc:"L'Electro-Harmonix Big Muff Pi est une légende du fuzz/distortion. Son massif, sustain infini, le mur de son de Gilmour et Corgan. Capture pédale seule."},
  "Pédales de drive + Electro-Harmonix Big Muff Pi":{emoji:"🎛️",refs:[{a:"David Gilmour",t:["Comfortably Numb"]},{a:"The Smashing Pumpkins",t:["Cherub Rock"]}],desc:"L'EHX Big Muff Pi : fuzz/distortion massif au sustain infini. Le son de Gilmour sur The Wall et de Corgan sur Siamese Dream. Capture pédale seule."},
  "Pédales de drive + Ibanez TS808 Tube Screamer":{emoji:"🎛️",refs:[{a:"Stevie Ray Vaughan",t:["Pride and Joy","Texas Flood"]},{a:"John Mayer",t:["Belief"]},{a:"The Edge",t:[]}],desc:"Le Tube Screamer TS808 est l'overdrive le plus célèbre au monde. Boost de médiums caractéristique, utilisé par SRV pour son son Texas Blues légendaire. Capture pédale seule."},
  "Pédales de drive + Klon Centaur":{emoji:"🎛️",refs:[{a:"Jeff Beck",t:[]},{a:"John Mayer",t:["Gravity"]},{a:"Matt Schofield",t:[]}],desc:"Le Klon Centaur est le Saint Graal des overdrives. Transparent, dynamique, il pousse l'ampli sans colorer le son. Original introuvable et très recherché. Capture pédale seule."},
  "Pédales de drive + REVV G4":{emoji:"🎛️",refs:[{a:"Rabea Massaad",t:[]},{a:"Pete Thorn",t:[]}],desc:"La REVV G4 est une pédale de distortion high gain moderne. Son serré et défini, parfaite pour le metal et le hard rock contemporain. Capture pédale seule."},
  "Pédales de drive + TC Electronic Vintage OD":{emoji:"🎛️",refs:[],desc:"Le TC Electronic Vintage Overdrive est un clone du Tube Screamer avec plus de headroom. Overdrive chaud et musical, bon pour le blues et le rock. Capture pédale seule."},
  "Pédales de drive + Maxon OD-9":{emoji:"🎛️",refs:[{a:"Stevie Ray Vaughan",t:[]},{a:"Mike Landau",t:[]}],desc:"Le Maxon OD-9 est le grand frère japonais du Tube Screamer (Ibanez est un rebrand de Maxon). Son légèrement plus ouvert et dynamique que le TS808. Capture pédale seule."},
  "Pédales de drive + Eagle Claw OD":{emoji:"🎛️",refs:[],desc:"L'Eagle Claw OD est un overdrive boutique à faible gain, transparent et dynamique. Idéal comme boost ou pour ajouter juste une touche de crunch. Capture pédale seule."},
  "Pédales de drive + DIY Candyman":{emoji:"🎛️",refs:[],desc:"Le DIY Candyman est un overdrive artisanal de type Klon. Son transparent avec un léger boost de médiums, réactif au toucher. Capture pédale seule."},
  "Pédales de drive + Soldano SLO-style OD":{emoji:"🎛️",refs:[{a:"Eric Clapton (80s)",t:[]},{a:"Warren DeMartini",t:[]}],desc:"Overdrive inspiré du canal lead du Soldano SLO-100. High gain articulé avec des médiums chantants, le son rock/metal des années 80-90. Capture pédale seule."},
  "Pédales de drive + Marshall Guv'nor Plus":{emoji:"🎛️",refs:[{a:"Gary Moore",t:["Still Got the Blues"]}],desc:"Le Marshall Guv'nor est la distortion Marshall en format pédale. Son british classique, médiums prononcés, crunch rock typique. Capture pédale seule."},
  "Pédales de drive + Marshall Jackhammer":{emoji:"🎛️",refs:[],desc:"Le Marshall Jackhammer est une pédale overdrive/distortion polyvalente. Du léger crunch au high gain, avec un EQ flexible. Capture pédale seule."},
  "Pédales de drive + Marshall-style Breaker OD":{emoji:"🎛️",refs:[{a:"Eric Clapton",t:["Beano album"]},{a:"John Mayer",t:[]}],desc:"Overdrive inspiré du Marshall Bluesbreaker, la pédale de légende de Clapton. Son crunch bluesy, dynamique et musical. Capture pédale seule."},
  "ENGL":{emoji:"🦅",refs:[{a:"Ritchie Blackmore",t:["Highway Star"]},{a:"Steve Morse",t:[]},{a:"Marty Friedman",t:[]}],desc:"Les amplis ENGL allemands offrent un son tight et agressif. Gain massif et articulé, idéal pour le metal européen et le hard rock moderne."},
  "EVH 5150":{emoji:"⚡",refs:[{a:"Eddie Van Halen",t:["Eruption","Panama"]},{a:"Wolfgang Van Halen",t:[]}],desc:"L'EVH 5150 est la version moderne du légendaire Peavey 5150. Conçu par Eddie Van Halen, c'est l'ampli metal/hard rock ultime. Gain massif, son percutant et articulé."},
  "Fender":{emoji:"🌅",refs:[{a:"Various Fender artists",t:[]}],desc:"Ampli Fender générique. Le son américain par excellence : cleans brillants, réponse cristalline, le socle de la musique populaire depuis les années 50."},
  "Fender 5E3 Tweed Deluxe":{emoji:"🎶",refs:[{a:"Neil Young",t:["Cinnamon Girl"]},{a:"Billy Gibbons",t:["La Grange"]},{a:"Larry Carlton",t:[]}],desc:"Le Fender 5E3 Tweed Deluxe est l'un des amplis les plus enregistrés de l'histoire. Breakup naturel et musical dès les premiers volumes. Son chaud, compressé, magique pour le blues et le rock."},
  "Fender 5E7 Bandmaster":{emoji:"🎶",refs:[{a:"Buddy Holly",t:["That'll Be the Day"]},{a:"Roy Buchanan",t:["Sweet Dreams"]}],desc:"Le Fender 5E7 Bandmaster Tweed de 1958 est un ampli 3x10 au son puissant et chaud. Version plus grande du Tweed Deluxe, il offre plus de headroom tout en gardant ce breakup naturel légendaire."},
  "Fender Bassman":{emoji:"🎷",refs:[{a:"Buddy Guy",t:["Stone Crazy"]},{a:"Jim Campilongo",t:[]}],desc:"Le Fender Bassman est l'ampli qui a inspiré les premiers Marshall. Son rond, chaud, crunch musical. Le son du blues et du rock'n'roll originel."},
  "Fender Blues Deluxe II":{emoji:"🌅",refs:[{a:"John Mayer",t:[]},{a:"Jonny Lang",t:[]}],desc:"Le Fender Blues Deluxe Reissue II est un combo 40W au son Tweed moderne. Réverb à ressort, gain naturel, le compagnon idéal du blues et du rock roots."},
  "Fender Cambridge":{emoji:"🌅",refs:[{a:"Syd Barrett",t:["Interstellar Overdrive"]}],desc:"Le Fender Cambridge Reverb est un combo à transistors vintage des années 60-70. Son propre et net, avec un charme lo-fi particulier. Utilisé par Syd Barrett aux débuts de Pink Floyd."},
  "Fender Hot Rod Twin":{emoji:"🌟",refs:[{a:"Session guitarists",t:[]}],desc:"Le Fender Hot Rod Twin est un ampli à fort headroom dérivé du Twin Reverb. Cleans immenses, canal drive ajouté. Polyvalent pour le live et le studio."},
  "Fender Princeton":{emoji:"🌅",refs:[{a:"Eric Clapton",t:["Unplugged"]},{a:"Mike Campbell",t:["Free Fallin'"]}],desc:"Le Fender Princeton Reverb est le petit ampli studio par excellence. Réverb à ressort légendaire, breakup naturel à volume modéré. Le son intime des grands enregistrements."},
  "Fender Pro Amp":{emoji:"🌅",refs:[{a:"Muddy Waters",t:["Hoochie Coochie Man"]},{a:"Stevie Ray Vaughan",t:[]}],desc:"Le Fender Pro Amp est un combo 1x15 au son plein et rond. Plus de basses que le Deluxe, idéal pour le blues de Chicago et les sonorités vintage."},
  "Fender Super Reverb":{emoji:"🌅",refs:[{a:"Stevie Ray Vaughan",t:["Texas Flood"]},{a:"Mike Campbell",t:[]}],desc:"Le Fender Super Reverb 4x10 est l'ampli de SRV sur ses premiers enregistrements. Son plein, projection puissante, breakup naturel. Le son du Texas Blues."},
  "Fender Texas Star":{emoji:"⭐",refs:[{a:"Eric Johnson",t:["Cliffs of Dover"]}],desc:"Le Fender Texas Star est un ampli prototype/boutique au son clair et articulé. Headroom important, dynamique exceptionnelle. Associé au son cristallin d'Eric Johnson."},
  "Fender Twin":{emoji:"🌟",refs:[{a:"Keith Richards",t:["Brown Sugar"]},{a:"Albert King",t:["Born Under a Bad Sign"]}],desc:"Le Fender Twin est la référence des cleans américains. Headroom immense, son brillant et défini. L'ampli des grands studios depuis les années 60."},
  "Fender Twin Reverb":{emoji:"🌟",refs:[{a:"Jerry Garcia",t:["Truckin'"]},{a:"B.B. King",t:["The Thrill Is Gone"]},{a:"Jazz Fusion artists",t:[]}],desc:"Le Fender Twin Reverb est la version avec réverb intégrée du Twin. Son propre légendaire, 85W de headroom pur. L'ampli jazz et clean par excellence."},
  "Fuzzy":{emoji:"🎛️",refs:[{a:"Jimi Hendrix",t:["Purple Haze"]}],desc:"Preset basé sur un circuit fuzz. Son saturé, compressé et sustain infini. Le son de Jimi Hendrix et du psychédélisme des années 60."},
  "Gallien-Krueger 800RB":{emoji:"🎸",refs:[{a:"Flea",t:["Give It Away"]},{a:"Robert Trujillo",t:[]}],desc:"Le GK 800RB est un ampli basse à transistors au son punchy et articulé. Le choix de Flea (Red Hot Chili Peppers) pour son attaque et sa clarté."},
  "Gibson Skylark":{emoji:"🎵",refs:[{a:"Chuck Berry",t:["Johnny B. Goode"]},{a:"Bo Diddley",t:["Who Do You Love"]}],desc:"Le petit ampli Gibson Skylark GA5 incarne le son roots des années 50. Breakup naturel à faible volume, chaleur vintage. Idéal pour le rockabilly et le blues."},
  "Hiwatt":{emoji:"🇬🇧",refs:[{a:"Pete Townshend",t:["Won't Get Fooled Again"]},{a:"David Gilmour",t:["Comfortably Numb"]}],desc:"Les amplis Hiwatt sont réputés pour leur headroom et leur clarté. Son british cristallin et puissant, le choix de Townshend et Gilmour."},
  "Marshall":{emoji:"🤘",refs:[{a:"Various rock artists",t:[]}],desc:"Ampli Marshall générique. Le son du rock par excellence depuis 1962. Grain british, crunch naturel, le mur de son qui a défini le genre."},
  "Marshall 18W":{emoji:"🎩",refs:[{a:"Eric Clapton",t:["Beano album"]},{a:"Jimmy Page",t:[]}],desc:"Le Marshall 18W est un petit ampli vintage très recherché. Son crunch naturel à faible volume, le son du Beano album de Clapton. Breakup musical et harmoniques riches."},
  "Marshall 1974X":{emoji:"🏺",refs:[{a:"Jimi Hendrix",t:["Purple Haze"]},{a:"Eric Clapton",t:[]}],desc:"Le Marshall 1974X est la réédition du combo 18W des années 60. Son crunch vintage authentique, breakup naturel. Le son des petits clubs de blues-rock des sixties."},
  "Marshall JTM45 / Super Lead":{emoji:"🎩",refs:[{a:"Eric Clapton",t:["Crossroads"]},{a:"Pete Townshend",t:["My Generation"]}],desc:"Le Marshall JTM45 / Super Lead combine les caractéristiques des deux circuits. Crunch bluesy, sustain naturel. Le fondement du son rock britannique."},
  "Marshall Major 200W (modifié)":{emoji:"🔊",refs:[{a:"Ritchie Blackmore",t:["Highway Star"]},{a:"John Entwistle",t:[]}],desc:"Le Marshall Major 200W modifié est un monstre de puissance. Volume et headroom extrêmes. Ritchie Blackmore (Deep Purple) l'utilisait pour ses solos perçants."},
  "Marshall Silver Jubilee":{emoji:"⚡",refs:[{a:"Slash",t:["November Rain"]},{a:"Alex Lifeson",t:["Tom Sawyer"]}],desc:"Le Marshall Silver Jubilee (2555) est un ampli mythique de 1987. Son crunch signature entre le Plexi et le JCM800. Le son de Slash sur Appetite for Destruction."},
  "Marshall Super 100":{emoji:"⚡",refs:[{a:"Jimi Hendrix",t:["All Along the Watchtower"]},{a:"Eric Clapton",t:[]},{a:"Jimmy Page",t:["Whole Lotta Love"]}],desc:"Le Marshall Super 100 (Plexi 100W) est l'ampli qui a défini le rock. Volume massif, crunch naturel, le son des années 60-70 dans les stades."},
  "Marshall Super Lead 100W":{emoji:"⚡",refs:[{a:"Angus Young",t:["Back in Black"]},{a:"Jimmy Page",t:["Stairway to Heaven"]},{a:"Jimi Hendrix",t:["Voodoo Child"]}],desc:"Le Marshall Super Lead 100W est le Plexi originel. Son brut et puissant, le mur de son qui a construit le hard rock. L'ampli le plus iconique de l'histoire du rock."},
  "Marshall Super Lead · Hiwatt Custom 100":{emoji:"🇬🇧",refs:[{a:"Pete Townshend",t:["Won't Get Fooled Again"]},{a:"David Gilmour",t:[]}],desc:"Combinaison Marshall Super Lead et Hiwatt Custom 100. Le meilleur des deux mondes britanniques : puissance Marshall et clarté Hiwatt."},
  "Matchless Brave":{emoji:"🎼",refs:[{a:"Tom Bukovac",t:[]},{a:"Session guitarists",t:[]}],desc:"Le Matchless Brave est un combo EL84 au son brillant et expressif. Crunch musical, dynamique remarquable. Apprécié des guitaristes de Nashville et des sessionmen."},
  "Matchless C30":{emoji:"🎼",refs:[{a:"Tom Petty",t:["American Girl"]},{a:"Mark Knopfler",t:[]}],desc:"Le Matchless C30 est l'héritier du Vox AC30. Son chimey et brillant, crunch musical. Plus articulé et moderne que l'original, idéal pour le rock et le pop-rock."},
  "Matchless Canyon":{emoji:"🎼",refs:[{a:"Session guitarists",t:[]}],desc:"Le Matchless Canyon est un ampli classe A au son ouvert et dynamique. Cleans cristallins, overdrive musical et réactif au toucher."},
  "Matchless Chieftain":{emoji:"🎼",refs:[{a:"Mark Knopfler",t:["Brothers in Arms"]},{a:"Tom Petty",t:[]}],desc:"Le Matchless Chieftain est le flagship de Matchless. 2 canaux, 40W, polyvalence exceptionnelle. Clean impeccable et overdrive chaud, le préféré de Mark Knopfler."},
  "Mesa Boogie":{emoji:"🔴",refs:[{a:"Carlos Santana",t:["Oye Como Va"]},{a:"Various artists",t:[]}],desc:"Les amplis Mesa Boogie sont synonymes de polyvalence et de gain articulé. Du clean cristallin au lead saturé, le son de la Californie depuis 1969."},
  "Mesa Boogie Mark II":{emoji:"🔴",refs:[{a:"Carlos Santana",t:["Oye Como Va"]},{a:"Keith Richards",t:[]}],desc:"Le Mesa Boogie Mark II est l'ampli qui a lancé le son Mesa. Gain articulé, EQ graphique, le son lead singing de Carlos Santana."},
  "Mesa Mark":{emoji:"🔴",refs:[{a:"John Petrucci",t:["Pull Me Under"]},{a:"Carlos Santana",t:["Smooth"]}],desc:"La série Mesa Mark définit le son lead moderne. Articulé, gain progressif, EQ ultra-flexible. Le choix de Petrucci et Santana."},
  "Mezzabarba MZero":{emoji:"🇮🇹",refs:[{a:"Matteo Mancuso",t:[]},{a:"Italian rock guitarists",t:[]}],desc:"Le Mezzabarba MZero est un ampli boutique italien au son moderne et raffiné. Clean transparent, overdrive organique. La nouvelle école du haut de gamme européen."},
  "Mezzabarba Trinity":{emoji:"🇮🇹",refs:[{a:"Matteo Mancuso",t:[]},{a:"Modern fusion players",t:[]}],desc:"Le Mezzabarba Trinity est un ampli 3 canaux italien haut de gamme. Du clean jazz au high gain moderne, avec une clarté et une dynamique exceptionnelles."},
  "Music Man HD130":{emoji:"🎸",refs:[{a:"Eric Clapton (70s)",t:[]},{a:"Mark Knopfler (early)",t:[]}],desc:"Le Music Man HD130 est un ampli à transistors/hybride conçu par Leo Fender. Son clean massif, headroom immense. Utilisé par Clapton et Knopfler dans les années 70."},
  "Orange":{emoji:"🍊",refs:[{a:"Jimmy Page",t:[]},{a:"Noel Gallagher",t:["Don't Look Back in Anger"]}],desc:"Les amplis Orange incarnent le son rock britannique chaud et saturé. Grain épais, midrange prononcé, le son de la scène rock UK depuis 1968."},
  "Orange OR120":{emoji:"🍊",refs:[{a:"Randy Rhoads",t:["Crazy Train"]},{a:"Geddy Lee",t:[]}],desc:"L'Orange OR120 est l'ampli classique de la marque. Son chaud et puissant, crunch british naturel. Utilisé par Randy Rhoads au début de sa carrière avec Ozzy."},
  "PRS Archon":{emoji:"🎸",refs:[{a:"Mark Tremonti",t:[]},{a:"Dustie Waring",t:[]}],desc:"Le PRS Archon est un ampli high gain moderne au son serré et articulé. Conçu par Paul Reed Smith, il offre des cleans transparents et un gain massif."},
  "Rockman Sustainor":{emoji:"🎧",refs:[{a:"Tom Scholz",t:["More Than a Feeling"]},{a:"Boston",t:["Peace of Mind"]}],desc:"Le Rockman Sustainor de Tom Scholz (Boston) est un préampli rack qui a défini le son AOR des années 80. Son compressé, sustain infini, chorus intégré."},
  "Stomp - Distortion":{emoji:"🎛️",refs:[{a:"Various artists",t:[]}],desc:"Captures de pédales de distortion via ToneX. Du crunch classique au high gain moderne, ces presets reproduisent le son de pédales de distortion emblématiques."},
  "Stomp - Fuzz":{emoji:"🎛️",refs:[{a:"Jimi Hendrix",t:["Purple Haze"]},{a:"David Gilmour",t:["Comfortably Numb"]}],desc:"Captures de pédales fuzz via ToneX. Le son saturé et compressé des années 60-70. Big Muff, Fuzz Face et autres légendes."},
  "Stomp - Overdrive":{emoji:"🎛️",refs:[{a:"Stevie Ray Vaughan",t:["Pride and Joy"]},{a:"John Mayer",t:[]}],desc:"Captures de pédales d'overdrive via ToneX. Tube Screamer, Klon, Blues Driver et autres classiques qui ont façonné le son du blues et du rock."},
  "Suhr SL67":{emoji:"🎸",refs:[{a:"Scott Henderson",t:[]},{a:"Doug Aldrich",t:[]}],desc:"Le Suhr SL67 est un ampli boutique inspiré du Marshall Plexi. Son crunch britannique raffiné, dynamique exceptionnelle. Le Plexi rêvé pour le guitariste moderne."},
  "Tone King Imperial":{emoji:"👑",refs:[{a:"Session guitarists",t:[]},{a:"Nashville players",t:[]}],desc:"Le Tone King Imperial est un ampli boutique américain au son Fender vintage premium. Atténuateur intégré, réverb exceptionnelle. Le son clean et breakup de Nashville."},
  "Trainwreck OD100":{emoji:"💥",refs:[{a:"Ken Fischer (builder)",t:[]},{a:"Brad Paisley",t:[]}],desc:"Le Trainwreck OD100 est l'un des amplis les plus rares et recherchés au monde. Construit par Ken Fischer, son gain organique et sa réponse au toucher sont légendaires."},
  "Two Rock":{emoji:"🌊",refs:[{a:"John Mayer",t:["Gravity"]},{a:"Matt Schofield",t:[]}],desc:"Les amplis Two Rock sont des boutiques californiens au son Dumble-like. Cleans aériens, overdrive musical et transparent. Le son du blues moderne haut de gamme."},
  "Unknown":{emoji:"❓",refs:[],desc:"Ampli non identifié. Preset capturé sans référence d'ampli spécifique."},
  "Laney Supergroup":{emoji:"🔥",refs:[{a:"Tony Iommi (Black Sabbath)",t:["Paranoid","Iron Man","War Pigs","Black Sabbath"]},{a:"Ritchie Blackmore",t:["Smoke on the Water (early)"]},{a:"Paul Gilbert",t:[]}],desc:"Le Laney Supergroup est l'ampli emblématique de Tony Iommi. Son mid-range agressif et son sustain épais ont défini le son du heavy metal originel. Un ampli britannique brut, sans compromis."},
  "Laney":{emoji:"🔥",refs:[{a:"Tony Iommi (Black Sabbath)",t:["Paranoid","Iron Man","War Pigs"]},{a:"Paul Gilbert",t:[]},{a:"Opeth",t:[]}],desc:"Laney est un fabricant britannique d'amplificateurs. Du Supergroup de Tony Iommi aux modernes IRT et GH, Laney couvre le spectre du blues au metal avec un caractère mid-range distinctif."},
  "Laney AOR":{emoji:"🔥",refs:[{a:"80s rock players",t:[]}],desc:"Le Laney AOR (Advanced Overdrive Response) est un ampli high-gain britannique des années 80. Son caractère agressif et ses médiums proéminents en font un classique du hard rock et du metal."},
  "Laney Lionheart":{emoji:"🦁",refs:[{a:"Blues-rock players",t:[]}],desc:"Le Laney Lionheart est un ampli Class A au son chaud et dynamique. Inspiré des amplis britanniques vintage, il excelle en clean et crunch avec un breakup musical et harmonique."}
};

// AMP_TAXONOMY
const AMP_TAXONOMY={
  "Fender Twin Silverface":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Twin":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Twin Reverb":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Blackface Twin":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Super Reverb":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Super":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Deluxe Reverb":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Deluxe":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender BF Deluxe":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Blues Deluxe II":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Princeton":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Bassman":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender Tweed Bassman":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender Blonde Bassman":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender Tweed Deluxe":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender 5E3 Tweed Deluxe":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender 5E7 Bandmaster":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender 5051 Tweed":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender Champ":{brand:"fender",family:"tweed",school:"fender_clean"},
  "Fender Concert":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Pro Amp":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Cambridge":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Hot Rod Twin":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Texas Star":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender Super S":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Fender":{brand:"fender",family:"blackface",school:"fender_clean"},
  "Marshall SL800":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall SL100":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall Plexi":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall Plexi 74":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall Super Lead 100W":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall Super 100":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall 1974X":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall JTM45":{brand:"marshall",family:"jtm",school:"marshall_crunch"},
  "Marshall JTM50":{brand:"marshall",family:"jtm",school:"marshall_crunch"},
  "Marshall JTM45 / Super Lead":{brand:"marshall",family:"jtm",school:"marshall_crunch"},
  "Marshall JCM800":{brand:"marshall",family:"jcm800",school:"marshall_crunch"},
  "Marshall JC800":{brand:"marshall",family:"jcm800",school:"marshall_crunch"},
  "Marshall 800":{brand:"marshall",family:"jcm800",school:"marshall_crunch"},
  "Marshall JCM900":{brand:"marshall",family:"jcm900",school:"marshall_crunch"},
  "Marshall SLT60":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall Silver Jubilee":{brand:"marshall",family:"jubilee",school:"marshall_crunch"},
  "Silver J":{brand:"marshall",family:"jubilee",school:"marshall_crunch"},
  "Marshall SB100":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall 18W":{brand:"marshall",family:"18w",school:"marshall_crunch"},
  "Marshall Major 200W (modifié)":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Marshall":{brand:"marshall",family:"plexi",school:"marshall_crunch"},
  "Vox AC30":{brand:"vox",family:"ac",school:"vox_chime"},
  "Budda V20":{brand:"budda",family:"class_a",school:"vox_chime"},
  "Matchless DC30":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Matchless HC15":{brand:"matchless",family:"hc",school:"vox_chime"},
  "Matchless C30":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Matchless Brave":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Matchless Canyon":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Matchless Chieftain":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Matchless Independence 35":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Independence 35":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Matchless":{brand:"matchless",family:"dc",school:"vox_chime"},
  "Dumble ODS":{brand:"dumble",family:"ods",school:"dumble_smooth"},
  "Dumble ODS 124":{brand:"dumble",family:"ods",school:"dumble_smooth"},
  "Dumble Deluxe":{brand:"dumble",family:"ods",school:"dumble_smooth"},
  "Two Rock Stevie G":{brand:"two_rock",family:"two_rock",school:"dumble_smooth"},
  "Two Rock Bloomfield":{brand:"two_rock",family:"bloomfield",school:"dumble_smooth"},
  "Two Rock":{brand:"two_rock",family:"two_rock",school:"dumble_smooth"},
  "Carr Sportsman":{brand:"carr",family:"boutique",school:"dumble_smooth"},
  "Benson Chimera":{brand:"benson",family:"boutique",school:"dumble_smooth"},
  "Mesa Boogie Rectifier":{brand:"mesa",family:"rectifier",school:"mesa_heavy"},
  "Mesa Rectifier":{brand:"mesa",family:"rectifier",school:"mesa_heavy"},
  "Mesa Boogie Mark II":{brand:"mesa",family:"mark",school:"mesa_heavy"},
  "Mesa Mark IV":{brand:"mesa",family:"mark",school:"mesa_heavy"},
  "Mesa Mark IIC+":{brand:"mesa",family:"mark",school:"mesa_heavy"},
  "Mesa Mark":{brand:"mesa",family:"mark",school:"mesa_heavy"},
  "Mesa Boogie":{brand:"mesa",family:"mark",school:"mesa_heavy"},
  "Hiwatt HG100":{brand:"hiwatt",family:"dr",school:"hiwatt_clean"},
  "Hiwatt Custom 100":{brand:"hiwatt",family:"dr",school:"hiwatt_clean"},
  "Hiwatt Wizard":{brand:"hiwatt",family:"wizard",school:"hiwatt_clean"},
  "Hiwatt":{brand:"hiwatt",family:"dr",school:"hiwatt_clean"},
  "Orange Rockerverb":{brand:"orange",family:"rockerverb",school:"marshall_crunch"},
  "Orange OR120":{brand:"orange",family:"or",school:"marshall_crunch"},
  "Orange GR100":{brand:"orange",family:"or",school:"marshall_crunch"},
  "Orange 120":{brand:"orange",family:"or",school:"marshall_crunch"},
  "Orange":{brand:"orange",family:"or",school:"marshall_crunch"},
  "Friedman BE-100":{brand:"friedman",family:"be",school:"marshall_crunch"},
  "Friedman HBE":{brand:"friedman",family:"be",school:"marshall_crunch"},
  "Friedman Buxom Betty":{brand:"friedman",family:"buxom",school:"marshall_crunch"},
  "Bogner Ecstasy":{brand:"bogner",family:"ecstasy",school:"marshall_crunch"},
  "Bogner G-Finger":{brand:"bogner",family:"gfinger",school:"marshall_crunch"},
  "Bogner Helioclipse":{brand:"bogner",family:"helio",school:"marshall_crunch"},
  "Soldano SLO-100":{brand:"soldano",family:"slo",school:"marshall_crunch"},
  "Soldano GP77":{brand:"soldano",family:"gp77",school:"marshall_crunch"},
  "Peavey 5150":{brand:"peavey",family:"5150",school:"mesa_heavy"},
  "EVH 5150":{brand:"peavey",family:"5150",school:"mesa_heavy"},
  "PRS Archon":{brand:"prs",family:"archon",school:"mesa_heavy"},
  "ENGL":{brand:"engl",family:"engl",school:"mesa_heavy"},
  "Diezel":{brand:"diezel",family:"diezel",school:"mesa_heavy"},
  "Roland JC-120":{brand:"roland",family:"jc",school:"fender_clean"},
  "Suhr SL67":{brand:"suhr",family:"sl67",school:"marshall_crunch"},
  "Tone King Imperial":{brand:"tone_king",family:"imperial",school:"fender_clean"},
  "Music Man HD130":{brand:"musicman",family:"hd",school:"fender_clean"},
  "Trainwreck OD100":{brand:"trainwreck",family:"od",school:"marshall_crunch"},
  "Bad Cat Cub":{brand:"badcat",family:"cub",school:"vox_chime"},
  "Amp Nation ODR":{brand:"amp_nation",family:"odr",school:"dumble_smooth"},
  "Amp Nation WOD":{brand:"amp_nation",family:"wod",school:"dumble_smooth"},
  "Mezzabarba MZero":{brand:"mezzabarba",family:"mzero",school:"marshall_crunch"},
  "Mezzabarba Trinity":{brand:"mezzabarba",family:"trinity",school:"marshall_crunch"},
  "Diesel Humbert":{brand:"diesel",family:"humbert",school:"marshall_crunch"},
  "D13 RG7":{brand:"d13",family:"rg7",school:"marshall_crunch"},
  "D13 AMP39":{brand:"d13",family:"amp39",school:"marshall_crunch"},
  "Gibson GA5 Skylark":{brand:"gibson",family:"skylark",school:"fender_clean"},
  "Gibson Skylark":{brand:"gibson",family:"skylark",school:"fender_clean"},
  "Cornfield Harle":{brand:"cornford",family:"harle",school:"marshall_crunch"},
  "Cornford HellCat":{brand:"cornford",family:"hellcat",school:"marshall_crunch"},
  "Ironlung":{brand:"ironlung",family:"ironlung",school:"marshall_crunch"},
  "Rouge Plate D50":{brand:"rouge",family:"d50",school:"fender_clean"},
  "Chandler GAV19T":{brand:"chandler",family:"gav19t",school:"fender_clean"},
  "Chandler 19T":{brand:"chandler",family:"gav19t",school:"fender_clean"},
  "Electro Dime":{brand:"electro",family:"dime",school:"mesa_heavy"},
  "Dr. Z":{brand:"drz",family:"drz",school:"vox_chime"},
  "Dr. Z Wreck":{brand:"drz",family:"wreck",school:"vox_chime"},
  "Jimi H20":{brand:"custom",family:"jimih20",school:"marshall_crunch"},
  "Rockman Sustainor":{brand:"rockman",family:"sustainor",school:"mesa_heavy"},
  "Talon 50":{brand:"talon",family:"talon50",school:"marshall_crunch"},
  "TSR20":{brand:"tsr",family:"tsr20",school:"vox_chime"},
  "TWS 2864-S":{brand:"tws",family:"2864s",school:"marshall_crunch"},
  "VMP-1":{brand:"vmp",family:"vmp1",school:"marshall_crunch"},
  "ZWREK":{brand:"zwrek",family:"zwrek",school:"marshall_crunch"},
  "Custom 30":{brand:"custom",family:"custom30",school:"vox_chime"},
  "Sons Amplification":{brand:"sons",family:"sons",school:"marshall_crunch"},
  "Amplifonics":{brand:"amplifonics",family:"amplifonics",school:"marshall_crunch"},
  "Reinguard T-36":{brand:"reinhardt",family:"rt36",school:"fender_clean"},
  "Laney Supergroup":{brand:"laney",family:"supergroup",school:"marshall_crunch"},
  "Laney Supergroup 100W":{brand:"laney",family:"supergroup",school:"marshall_crunch"},
  "Laney AOR":{brand:"laney",family:"aor",school:"marshall_crunch"},
  "Laney GH100L":{brand:"laney",family:"gh",school:"marshall_crunch"},
  "Laney VH100":{brand:"laney",family:"vh",school:"marshall_crunch"},
  "Laney VC50":{brand:"laney",family:"vc",school:"marshall_crunch"},
  "Laney VC30":{brand:"laney",family:"vc",school:"vox_chime"},
  "Laney Lionheart":{brand:"laney",family:"lionheart",school:"vox_chime"},
  "Laney IRT":{brand:"laney",family:"irt",school:"marshall_crunch"},
  "Laney":{brand:"laney",family:"supergroup",school:"marshall_crunch"},
};

// Catalogues des createurs de presets (packs disponibles a l'achat)
const EXTERNAL_PACK_CATALOG = [
  {creator:"The Studio Rats",url:"thestudiorats.com",packs:[
    {name:"Marshall Plexi",amps:["marshall plexi","plexi"]},
    {name:"Marshall JTM",amps:["marshall jtm","jtm45","jtm50"]},
    {name:"Marshall JCM900",amps:["marshall jcm900","jcm 900"]},
    {name:"Marshall 800 SL",amps:["marshall 800","jcm800","super lead"]},
    {name:"Marshall SLT60",amps:["silver jubilee","marshall jubilee","slt60"]},
    {name:"Silver Jubilee",amps:["silver jubilee","marshall 2555"]},
    {name:"Fender Blackface Bassman",amps:["fender bassman","bassman"]},
    {name:"Fender Silverface Twin",amps:["fender twin","twin reverb","silverface"]},
    {name:"Fender Concert",amps:["fender concert"]},
    {name:"Fender Super S",amps:["fender super","super reverb"]},
    {name:"Deluxe Reverb II",amps:["deluxe reverb","fender deluxe"]},
    {name:"Bumble Deluxe",amps:["dumble","dumble deluxe","overdrive special"]},
    {name:"Mesa Boogie IIC+",amps:["mesa","mesa boogie","mark iic","mark ii"]},
    {name:"Mesa Rectifier",amps:["rectifier","dual rectifier","mesa rectifier"]},
    {name:"Bogner Ecstasy 101B",amps:["bogner ecstasy","bogner 101b"]},
    {name:"Bogner Helioclipse",amps:["bogner helioclipse"]},
    {name:"Matchless HC15",amps:["matchless hc15","matchless"]},
    {name:"Matchless Independence",amps:["matchless independence"]},
    {name:"Two Rock Bloomfield",amps:["two rock bloomfield","two rock"]},
    {name:"Two Rock Stevie G",amps:["two rock stevie","stevie g"]},
    {name:"Friedman BE/DE",amps:["friedman be","friedman de"]},
    {name:"Hiwatt HG100",amps:["hiwatt"]},
    {name:"Soldano 100",amps:["soldano","slo-100","slo100"]},
    {name:"D13",amps:["divided by 13","d13"]},
    {name:"British Chime (Budda V20)",amps:["budda","superdrive v20"]},
    {name:"British Rock (Vox DC30)",amps:["vox ac30","vox dc30","ac30"]},
    {name:"Roland JC",amps:["roland jc","jazz chorus"]},
    {name:"Jimi Hendrix 20W",amps:["marshall 20w","hendrix"]},
  ]},
  {creator:"Amalgam Audio",url:"amalgamaudio.com",packs:[
    {name:"Laney Supergroup",amps:["laney","laney supergroup","laney super"]},
    {name:"Orange OR120",amps:["orange or120","orange 120"]},
    {name:"Orange Rockerverb",amps:["orange rockerverb"]},
    {name:"Marshall JMP",amps:["marshall jmp"]},
    {name:"Marshall Plexi Super Bass",amps:["marshall plexi","plexi","super bass"]},
    {name:"Vox AC30 Top Boost",amps:["vox ac30","ac30 top boost"]},
    {name:"Fender Princeton",amps:["fender princeton","princeton reverb","princeton"]},
    {name:"Fender Super Reverb",amps:["fender super reverb","super reverb"]},
    {name:"Fender Vibrolux",amps:["fender vibrolux","vibrolux"]},
    {name:"Fender Champ",amps:["fender champ","champ"]},
    {name:"Supro Thunderbolt",amps:["supro"]},
    {name:"Ampeg VT-22",amps:["ampeg vt","ampeg v"]},
    {name:"Traynor YBA-1",amps:["traynor"]},
    {name:"Peavey 5150",amps:["peavey 5150","5150","evh 5150"]},
    {name:"Park 75",amps:["park 75","park amp"]},
    {name:"Hiwatt DR103",amps:["hiwatt"]},
    {name:"Carr Mercury V",amps:["carr mercury","carr"]},
    {name:"Tone King Imperial",amps:["tone king"]},
    {name:"Two-Rock TS-1",amps:["two rock","two-rock"]},
    {name:"Mesa Boogie (Amp Kit V)",amps:["mesa boogie","mesa"]},
    {name:"Soldano SL100 (Amp Kit V)",amps:["soldano","slo-100"]},
    {name:"Friedman B100D (Amp Kit V)",amps:["friedman"]},
    {name:"Engl Powerball (Amp Kit V)",amps:["engl"]},
    {name:"Marshall JC2000 (Amp Kit V)",amps:["marshall jcm2000","jcm2000"]},
  ]},
  {creator:"JS Custom Tones",url:"jscustomtones.com",packs:[
    {name:"Dumble ODS",amps:["dumble ods","dumble overdrive","dumble"]},
    {name:"Two Stone",amps:["two rock","two stone"]},
    {name:"Z-Wreck",amps:["dr. z","z-wreck"]},
    {name:"Matchless",amps:["matchless"]},
    {name:"AC44 (Vox AC30)",amps:["vox ac30","ac30","vox"]},
    {name:"Purple Plexi (Marshall)",amps:["marshall plexi","plexi"]},
  ]},
  {creator:"ML Sound Lab",url:"mlsoundlab.com",packs:[
    {name:"MARS 800 (Marshall JCM800)",amps:["marshall jcm800","marshall 800","jcm800"]},
    {name:"VX30 (Vox AC30)",amps:["vox ac30","ac30","vox"]},
    {name:"FNDR Deluxe (Fender Deluxe)",amps:["fender deluxe","deluxe reverb"]},
    {name:"JAZZ 120 (Roland JC-120)",amps:["roland jc","jazz chorus","jc-120"]},
    {name:"MEGA Rec (Mesa Rectifier)",amps:["mesa rectifier","rectifier","dual rec"]},
    {name:"MEGA MK4 (Mesa Mark IV)",amps:["mesa mark iv","mark iv","mesa mark"]},
    {name:"ORNG Rock (Orange)",amps:["orange"]},
    {name:"FMAN BE (Friedman BE)",amps:["friedman be","friedman"]},
  ]},
  {creator:"Tone Junkie",url:"tonejunkiestore.com/tonex",packs:[
    {name:"Sparkle 30 (Matchless SC30)",amps:["matchless"]},
    {name:"97 Match Chief (Matchless Chieftain)",amps:["matchless chieftain","matchless"]},
    {name:"Match Mini (Matchless Mini)",amps:["matchless"]},
    {name:"Match Brave (Matchless Brave)",amps:["matchless brave","matchless"]},
    {name:"62 Pro Amp (Fender Pro)",amps:["fender pro"]},
    {name:"64 Tuxedo Prince (Fender Princeton)",amps:["fender princeton","princeton"]},
    {name:"65 Deluxe Reverb",amps:["fender deluxe","deluxe reverb"]},
    {name:"57 5E3 Deluxe",amps:["fender deluxe","5e3","tweed deluxe"]},
    {name:"58 5E7 Bandmaster",amps:["fender bandmaster","bandmaster"]},
    {name:"68 Twin 15",amps:["fender twin","twin reverb"]},
    {name:"65 Vox Cambridge",amps:["vox cambridge","vox"]},
    {name:"66 AC30",amps:["vox ac30","ac30"]},
    {name:"AC44",amps:["vox ac30","ac30"]},
    {name:"AC50",amps:["vox ac50","ac50"]},
    {name:"AC10 SRT+",amps:["vox ac10"]},
    {name:"68 Purple Plexi",amps:["marshall plexi","plexi"]},
    {name:"74 Purple Plexi",amps:["marshall plexi","plexi"]},
    {name:"JMP 2040",amps:["marshall jmp","jmp"]},
    {name:"MARS 2553 (Silver Jubilee)",amps:["marshall jubilee","silver jubilee","2553"]},
    {name:"DMBL ODRV DLX (Dumble ODS)",amps:["dumble","dumble ods","overdrive special"]},
    {name:"DMBL ODS 124 (Dumble 124)",amps:["dumble","dumble ods"]},
    {name:"DMBL WATT (Dumble Watt)",amps:["dumble"]},
    {name:"Tweed DMBLuxe (Dumble Tweed)",amps:["dumble"]},
    {name:"Wreck Collection (Dr. Z)",amps:["dr. z","z-wreck"]},
    {name:"58 Ampeg Rocket",amps:["ampeg rocket","ampeg"]},
    {name:"BC30 (Bad Cat 30)",amps:["bad cat"]},
    {name:"BC15 (Bad Cat 15)",amps:["bad cat"]},
    {name:"BC Cub 40 (Bad Cat Cub)",amps:["bad cat cub","bad cat"]},
    {name:"Hot Cat 40 (Bad Cat Hot Cat)",amps:["bad cat hot cat","hot cat"]},
    {name:"GainStar 15",amps:["gainstar","high gain"]},
    {name:"JH20 (Jimi Hendrix 20W)",amps:["hendrix","marshall 20"]},
    {name:"MNSTR (Monster)",amps:["high gain","monster"]},
    {name:"18 Watt Custom",amps:["18 watt","marshall 18"]},
    {name:"60s Skylark",amps:["skylark","gibson skylark"]},
    {name:"Mars Astra",amps:["marshall","astra"]},
    {name:"65 JM BluesMaker",amps:["bluesmaker","blues"]},
  ]},
  {creator:"Jason Sadites",url:"sadites.com/tonex-presets",packs:[
    {name:"Cali V (Mesa Mark V)",amps:["mesa mark v","mark v","mesa boogie"]},
    {name:"Voxy 20 (Morgan/Vox)",amps:["vox","morgan"]},
    {name:"Deluxe (Fender Deluxe)",amps:["fender deluxe","deluxe reverb"]},
    {name:"Vintage 67 BMaster (Fender Bassman)",amps:["fender bassman","bassman"]},
    {name:"Vintage 63 PrinceTone (Princeton)",amps:["fender princeton","princeton"]},
    {name:"Vintage 61 Brown Soup",amps:["fender brown","fender"]},
    {name:"Vintage Dlx Vrb (Deluxe Reverb)",amps:["deluxe reverb","fender deluxe"]},
    {name:"Vintage Brit 2203 (Marshall JCM800)",amps:["marshall jcm800","jcm800","marshall 800"]},
    {name:"Ultimate Plexi (Marshall Plexi)",amps:["marshall plexi","plexi"]},
    {name:"D-Style / Dumbl'ish (Dumble)",amps:["dumble","d-style"]},
    {name:"D-Classic (Fuchs ODS Classic)",amps:["fuchs","dumble"]},
    {name:"Xstasy Red (Bogner Ecstasy)",amps:["bogner ecstasy","bogner"]},
    {name:"Fried-Guy (Friedman)",amps:["friedman"]},
    {name:"Ravv Purple / Gen 100 (REVV)",amps:["revv"]},
    {name:"Kudos",amps:["kudos"]},
    {name:"Cheef-Tan TR (Chieftain)",amps:["chieftain","matchless"]},
  ]},
  {creator:"New Vintage Audio",url:"newvintageaudio.com",packs:[
    {name:"67 Plexi Pack",amps:["marshall plexi","plexi"]},
    {name:"Metal Pack",amps:["mesa rectifier","peavey 5150","5150","high gain"]},
    {name:"Peaveys Pack",amps:["peavey 5150","5150","peavey"]},
    {name:"Crystal Cleans Pack",amps:["fender twin","fender deluxe","clean"]},
    {name:"Handwired Pack",amps:["marshall","vox","handwired"]},
    {name:"Small Amps Pack",amps:["fender champ","princeton","small amp"]},
  ]},
  {creator:"Liveplayrock",url:"liveplayrock.com/collections/tonex-ik-multimedia",packs:[
    {name:"Marshall JCM800 Pack",amps:["marshall jcm800","jcm800","marshall 800"]},
    {name:"Dual Rectifier Pack",amps:["mesa rectifier","dual rectifier","rectifier"]},
    {name:"Mark V Pack",amps:["mesa mark v","mark v"]},
    {name:"EVH 5150 Pack",amps:["evh 5150","5150","peavey 5150"]},
  ]},
  {creator:"MirrorProfiles",url:"mirrorprofiles.myshopify.com",packs:[
    {name:"Gain Legends (70s-2000s)",amps:["marshall","mesa","high gain"]},
  ]},
  {creator:"ChopTones",url:"choptones.com",packs:[
    {name:"Marshall Collection",amps:["marshall","plexi","jcm800"]},
    {name:"Fender Collection",amps:["fender","twin","deluxe"]},
    {name:"Mesa Collection",amps:["mesa","rectifier","mark"]},
    {name:"High Gain Collection",amps:["5150","soldano","high gain"]},
  ]},
];

